name: Windows EXE Build

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==5.13.0
        pip install PyMuPDF==1.23.21
        pip install Pillow==10.2.0
        pip install PySide6==6.6.1

    - name: Clean PyInstaller cache (optional but helpful)
      run: |
        if (Test-Path build) { Remove-Item build -Recurse -Force }
        if (Test-Path dist) { Remove-Item dist -Recurse -Force }
        if (Test-Path PDFtoJPG.spec) { Remove-Item PDFtoJPG.spec -Force }

    - name: Run build script
      run: |
        python build_app.py

    - name: Upload EXE as artifact (for debugging)
      uses: actions/upload-artifact@v4
      with:
        name: PDFtoJPG-exe
        path: dist/PDFtoJPG.exe

    - name: Upload EXE to GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        files: dist/PDFtoJPG.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}


